printWidth = 80
singleQuote = false
tabWidth = 4

[[overrides]]
files = [ "*.js" ]

[overrides.options]
semi = true
singleQuote = true
tabWidth = 2

[[overrides]]
files = [ "*.yml" ]

[overrides.options]
tabWidth = 2
